imports:
    - { resource: security.yml }
parameters:
    user_login.default_target_path: home     
framework:
    secret: ThisToksdfhjjenIsNotSoasdasas565a5s4dSecretChangeIt
    validation:
        enable_annotations: true
    templating:
        engines: ["twig"]
    default_locale: ru
    translator:
        enabled: true
        fallback: ru
    session:
        cookie_lifetime: 0
        cookie_httponly: true
        cookie_secure: false
        gc_maxlifetime: 300
        gc_probability: 100
        gc_divisor: 100
    serializer:
        enabled: true
doctrine:
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            name:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Entity"
                prefix: AppBundle\Entity
                is_bundle: false
sensio_framework_extra:
    router: 
        annotations: true
    request:
        converters: false
    view:
        annotations: true
    cache:
        annotations: false
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"]
jms_i18n_routing:
    default_locale: ru
    locales: [ua, ru]
    strategy: prefix_except_default
swiftmailer:
    transport: sendmail                   
    host: mail.ukraine.com.ua
monolog:
    handlers:
        main:
            level: debug
            type: stream
            path: "%kernel.logs_dir%/app.log"            
            channels: [app]
            #channels: ['!php', '!security', '!request']
        doctrine:
            level: alert
            type: stream
            path: "%kernel.logs_dir%/doctrine.log"            
            channels: [doctrine]
            