imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing-dev.yml"   
    profiler:
        enabled: true
        collect: true
        only_exceptions: false    
        matcher:
            enabled: true
            ip: 127.0.0.1
doctrine:
    dbal:
        driver: pdo_mysql
        host: 127.0.0.1
        port: null
        dbname: shop_db
        user: shop_db
        password: ohhDOyD75c
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        logging: true
swiftmailer:
    transport: sendmail                   
    host: localhost
    disable_delivery: false        
web_profiler:
    toolbar: true
    intercept_redirects: false