imports:
    - { resource: security.yml }
    - { resource: "parameters.yml" }    
parameters:
    user_login.default_target_path: home
    locale: ua     
framework:
    secret: ThisToksdfhjjenIsNotSoasdasas565a5s4dSecretChangeIt
    validation:
        enable_annotations: true
    templating:
        engines: ["twig"]
    assets:
      base_urls: 
          - "http://druk-reklama.com.ua/web/"
          - "http://z-reklama.shop/web/"
      packages:
         block:
            base_path: "/web/content/block/image/"
    default_locale: ua
    translator:
        enabled: true
        fallback: ua
    session:
        cookie_lifetime: 0
        cookie_httponly: true
        cookie_secure: false
        gc_maxlifetime: 300
        gc_probability: 100
        gc_divisor: 100
    serializer:
        enabled: true
    form: ~
    csrf_protection: ~    
doctrine:
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            name:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Entity"
                prefix: AppBundle\Entity
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\UserEntity
    from_email:
        address: "%mailer_addres%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationFormType
            validation_groups:
                - AppBundle_Registration
                - Default
        confirmation:
            enabled: true
stof_doctrine_extensions:
    default_locale: ua
    orm:
        default:
            tree: true                
sensio_framework_extra:
    router: 
        annotations: true
    request:
        converters: false
    view:
        annotations: true
    cache:
        annotations: false
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"]
jms_i18n_routing:
    default_locale: ua
    locales: [ua, ru]
    strategy: prefix_except_default
twig:
    paths:
        "%kernel.root_dir%/../app/Resources/views/": view
services:
    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@liip_imagine.cache.manager", "%kernel.root_dir%", "@security.token_storage", "@OrderDAO", "@session", "@oneup_uploader.orphanage_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }
    app.custom_oneup_uploader_namer:
        class: AppBundle\Service\OneupUploaderNamer
        arguments: ["@security.token_storage"]            
    app.form.registration:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [AppBundle\Entity\UserEntity]
        tags:
            - { name: form.type, alias: app_user_registration }
    app.uaser.fosRegistrationListener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_subscriber }
monolog:
    handlers:
        main:
            level: debug
            type: stream
            path: "%kernel.logs_dir%/app.log"            
            channels: [app]
            #channels: ['!php', '!security', '!request']
        doctrine:
            level: alert
            type: stream
            path: "%kernel.logs_dir%/doctrine.log"            
            channels: [doctrine]
ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            #locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            fullscreen: false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true # defaults to false (true|false) 
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']
                        #upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        #upload_deny: ['all']
                        upload_max_size: 100M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                        url: web/uploads
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:                                 
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:                                        
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template                                    
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template                                
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../"
                cache_prefix: "web/thumbnails"
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../"
    driver: imagick
    cache: default
    data_loader: default
    default_image: null
    
    filter_sets:
        slider_thumb_big:
            quality: 95
            filters:
                thumbnail: { size: [1920, 1080], mode: outbound }
        slider_thumb_small:
            quality: 95
            filters:
                thumbnail: { size: [250, 150], mode: outbound }
        order_tiff:
            format: jpg 
            quality: 95
            filters:
                thumbnail: { size: [345, 215], mode: outbound }			    
ivory_google_map:
    map:
        debug: "%kernel.debug%"
        api_key: "AIzaSyCdm8y8lSYG79Y31FvkK-83jVxBnKDctQA"                        
oneup_uploader:
    mappings:
        gallery:
            frontend: plupload
            storage:
                directory: "%kernel.root_dir%/..%user_order_uploads_dir%"
            allowed_mimetypes:
                #image/jpeg : ['jpg', 'jpeg', 'jpe']
                image/tiff : ['tiff', 'tif']
                application/octet-stream : ['cdr']  
                application/zip : ['cdr']                               
                #text/plain : ['txt'] 
            disallowed_mimetypes: []
            root_folder: false
            # Set max_size to -1 for gracefully downgrade this number to the systems max upload size.
            max_size: 9223372036854775807
            use_orphanage: true
            enable_progress: true
            enable_cancelation: false
            namer: app.custom_oneup_uploader_namer
    orphanage:
            maxage: 86400
            directory: "%kernel.root_dir%/../web/orphanage/oneup_uploader"
    chunks:
        maxage: 86400
        storage:
            directory: "%kernel.root_dir%/../web/orphanage/oneup_uploader/chunks"                        