imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing-prod.yml"
doctrine:
    dbal:
        driver: pdo_mysql
        host: 127.0.0.1
        port: null
        dbname: shop_db
        user: shop_db
        password: ohhDOyD75c
        charset: utf8mb4
        logging: true
swiftmailer:
    transport: sendmail                   
    host: localhost
    disable_delivery: false        
