imports:
    - { resource: security.yml }
parameters:
    user_login.default_target_path: home     
framework:
    secret: ThisToksdfhjjenIsNotSoasdasas565a5s4dSecretChangeIt
    validation:
        enable_annotations: true
    templating:
        engines: ["twig"]
    assets:
      base_urls: ["http://z-reklama.shop/web/"]
    default_locale: ru
    translator:
        enabled: true
        fallback: ru
    session:
        cookie_lifetime: 0
        cookie_httponly: true
        cookie_secure: false
        gc_maxlifetime: 300
        gc_probability: 100
        gc_divisor: 100
    serializer:
        enabled: true
    form: ~
doctrine:
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            name:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Entity"
                prefix: AppBundle\Entity
                is_bundle: false
sensio_framework_extra:
    router: 
        annotations: true
    request:
        converters: false
    view:
        annotations: true
    cache:
        annotations: false
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"]
jms_i18n_routing:
    default_locale: ru
    locales: [ua, ru]
    strategy: prefix_except_default
swiftmailer:
    transport: sendmail                   
    host: mail.ukraine.com.ua
monolog:
    handlers:
        main:
            level: debug
            type: stream
            path: "%kernel.logs_dir%/app.log"            
            channels: [app]
            #channels: ['!php', '!security', '!request']
        doctrine:
            level: alert
            type: stream
            path: "%kernel.logs_dir%/doctrine.log"            
            channels: [doctrine]
ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            #locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            fullscreen: false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true # defaults to false (true|false) 
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']
                        #upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        #upload_deny: ['all']
                        upload_max_size: 100M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
                        url: web/uploads