imports:
    - { resource: config.yml }
framework:
    router:
        resource: "%kernel.root_dir%/config/routing-prod.yml"
doctrine:
    dbal:
        driver: pdo_mysql
        host: dstepa00.mysql.ukraine.com.ua
        port: null
        dbname: dstepa00_av
        user: dstepa00_av
        password: m4uuh6bk
        charset: UTF8
        logging: true
        