_general:     
    resource: "@AppBundle/controller/DefaultController.php"
    type: annotation
_app:
    resource: "@AppBundle/controller/"
    type: annotation
_ProfilerBundle_wdt:    
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml" 
    prefix: "/_wdt"
_ProfilerBundle_profiler:      
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml" 
    prefix: "/_profiler"