security:
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
        fos_userbundle:
            id: fos_user.user_provider.username                
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha1
            encode-as-base64: false
            iterations: 1      
    firewalls:
        main:
            provider: chain_provider
            anonymous: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
            remember_me:
                secret: "%secret%"
                lifetime: 86400
                path: /
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/efconnect, role: ROLE_USER }
      #- { path: ^/elfinder, role: ROLE_USER }