security:
    providers:
        in_memory:
            memory:
              users:
                      ryan:
                          password: ryanpass
                          roles: 'ROLE_USER'
                      admin:
                          password: admin
                          roles: 'ROLE_ADMIN' 
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/edit_category, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      #- { path: ^/efconnect, role: ROLE_USER }
      #- { path: ^/elfinder, role: ROLE_USER }